spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sqltest?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 136wswm

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update

# 基础知识1：https://www.cnblogs.com/wmyskxz/p/9010832.html?tdsourcetag=s_pcqq_aiomsg
# 基础知识2：https://www.cnblogs.com/ityouknow/p/7594801.html?tdsourcetag=s_pcqq_aiomsg